#!/usr/bin/env bash
# Generate Proxmox post-installation script
#
# This script reads SSH host keys from secrets/proxmox/ssh.enc.yaml and generates
# a bash script that can be pasted into the OVH installation wizard.
#
# The generated script will:
# - Set SSH host keys on the Proxmox server
# - Set proper permissions
# - Restart SSH service
#
# Usage:
#   ./generate-proxmox-install-script.sh [OPTIONS] [OUTPUT_FILE]
#
# Options:
#   --base64, -b    Output base64-encoded script (required by OVH web UI)
#
# Examples:
#   ./generate-proxmox-install-script.sh                    # Output to stdout
#   ./generate-proxmox-install-script.sh --base64           # Output base64 to stdout
#   ./generate-proxmox-install-script.sh script.sh          # Save to file
#   ./generate-proxmox-install-script.sh --base64 out.txt   # Save base64 to file

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SECRETS_FILE="${REPO_ROOT}/secrets/proxmox/ssh.enc.yaml"
AGE_KEY_FILE="${REPO_ROOT}/secrets/.age-key.txt"
BASE64_ENCODE=false
OUTPUT_FILE=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --base64|-b)
            BASE64_ENCODE=true
            shift
            ;;
        -*)
            echo "❌ Error: Unknown option: $1" >&2
            echo "Usage: $0 [--base64] [OUTPUT_FILE]" >&2
            exit 1
            ;;
        *)
            OUTPUT_FILE="$1"
            shift
            ;;
    esac
done

# Check dependencies
if ! command -v sops &> /dev/null; then
    echo "❌ Error: sops is not installed" >&2
    exit 1
fi

if ! command -v yq &> /dev/null; then
    echo "❌ Error: yq is not installed" >&2
    exit 1
fi

# Check if secrets file exists
if [ ! -f "${SECRETS_FILE}" ]; then
    echo "❌ Error: Secrets file not found: ${SECRETS_FILE}" >&2
    exit 1
fi

# Check if age key exists
if [ ! -f "${AGE_KEY_FILE}" ]; then
    echo "❌ Error: Age key not found: ${AGE_KEY_FILE}" >&2
    exit 1
fi

# Decrypt secrets and extract host keys
echo "📖 Reading host keys from secrets..." >&2

ED25519_PRIVATE=$(SOPS_AGE_KEY_FILE="${AGE_KEY_FILE}" sops -d "${SECRETS_FILE}" | yq -r '.ssh.host_keys.ed25519.private')
ED25519_PUBLIC=$(SOPS_AGE_KEY_FILE="${AGE_KEY_FILE}" sops -d "${SECRETS_FILE}" | yq -r '.ssh.host_keys.ed25519.public')
RSA_PRIVATE=$(SOPS_AGE_KEY_FILE="${AGE_KEY_FILE}" sops -d "${SECRETS_FILE}" | yq -r '.ssh.host_keys.rsa.private')
RSA_PUBLIC=$(SOPS_AGE_KEY_FILE="${AGE_KEY_FILE}" sops -d "${SECRETS_FILE}" | yq -r '.ssh.host_keys.rsa.public')

# Validate that we got the keys
if [ -z "$ED25519_PRIVATE" ] || [ "$ED25519_PRIVATE" = "null" ]; then
    echo "❌ Error: Failed to extract ed25519 private key" >&2
    exit 1
fi

echo "✅ Host keys extracted successfully" >&2
echo "" >&2

# Generate the installation script
generate_script() {
    cat <<'SCRIPT_HEADER'
#!/bin/bash
# Proxmox Post-Installation Script
# Generated by scripts/generate-proxmox-install-script.sh
#
# This script sets SSH host keys to pre-generated values
# to avoid TOFU (Trust On First Use) security issues

set -euo pipefail

echo "Setting SSH host keys..."

# Write ed25519 host key
cat > /etc/ssh/ssh_host_ed25519_key <<'EOF_ED25519_PRIV'
SCRIPT_HEADER

    echo "$ED25519_PRIVATE"

    cat <<'SCRIPT_MID1'
EOF_ED25519_PRIV

cat > /etc/ssh/ssh_host_ed25519_key.pub <<'EOF_ED25519_PUB'
SCRIPT_MID1

    echo "$ED25519_PUBLIC"

    cat <<'SCRIPT_MID2'
EOF_ED25519_PUB

# Write RSA host key
cat > /etc/ssh/ssh_host_rsa_key <<'EOF_RSA_PRIV'
SCRIPT_MID2

    echo "$RSA_PRIVATE"

    cat <<'SCRIPT_MID3'
EOF_RSA_PRIV

cat > /etc/ssh/ssh_host_rsa_key.pub <<'EOF_RSA_PUB'
SCRIPT_MID3

    echo "$RSA_PUBLIC"

    cat <<'SCRIPT_FOOTER'
EOF_RSA_PUB

# Set proper permissions
chmod 600 /etc/ssh/ssh_host_ed25519_key
chmod 644 /etc/ssh/ssh_host_ed25519_key.pub
chmod 600 /etc/ssh/ssh_host_rsa_key
chmod 644 /etc/ssh/ssh_host_rsa_key.pub

# Restart SSH service to load new keys
systemctl restart sshd || systemctl restart ssh

echo "✅ SSH host keys configured successfully"
SCRIPT_FOOTER
}

# Output the script
if [ "$BASE64_ENCODE" = true ]; then
    # Base64 encode the script (required by OVH web UI)
    if [ -n "$OUTPUT_FILE" ]; then
        generate_script | base64 > "$OUTPUT_FILE"
        echo "✅ Base64-encoded installation script written to: ${OUTPUT_FILE}" >&2
        echo "" >&2
        echo "You can now copy the contents of this file to the OVH installation wizard." >&2
    else
        echo "📋 Base64-encoded installation script (copy/paste this into OVH wizard):" >&2
        echo "========================================================================" >&2
        echo "" >&2
        generate_script | base64
    fi
else
    # Output plain script
    if [ -n "$OUTPUT_FILE" ]; then
        generate_script > "$OUTPUT_FILE"
        chmod +x "$OUTPUT_FILE"
        echo "✅ Installation script written to: ${OUTPUT_FILE}" >&2
        echo "" >&2
        echo "To use in OVH web UI, encode it with: base64 < ${OUTPUT_FILE}" >&2
    else
        echo "📋 Generated installation script:" >&2
        echo "==================================" >&2
        echo "" >&2
        echo "⚠️  Note: OVH web UI requires base64 encoding. Use --base64 flag." >&2
        echo "" >&2
        generate_script
    fi
fi
