---
# Role metadata
galaxy_info:
  author: Project Racknarok
  description: Configure Proxmox networking including vRack bridges
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies: []
